### ISSUE TITLE
Archiving TODO headings not working

### ISSUE THREAD

**Issue by jgollenz** [akinsho/org-bullets.nvim#11]
![error](https://user-images.githubusercontent.com/12050098/147750791-32a5d64f-8152-4fb0-9023-6dcb465f670a.gif)

I am archiving the TODO heading with `<leader>o$`
After the archiving no more bullets are substituted

**Comment by TravonteD** [comment]
It looks like the archive action is breaking the ext mark. We may need to refresh them when that happens, however I don't believe this plugin was meant to depend on `nvim-orgmode`

**Comment by jgollenz** [comment]
> however I don't believe this plugin was meant to depend on `nvim-orgmode`

I think [this](https://github.com/akinsho/org-bullets.nvim/blob/main/README.md?plain=1#L6) says otherwise

**Comment by TravonteD** [comment]
I stand corrected 👍🏾

**Comment by akinsho** [comment]
Sorry both haven't had much time to look into any issue or PRs on this repo, swamped with other stuff outside of OSS and can barely get through just triaging stuff on my other projects. Will get back to this when next I have time or happy to review any PRs anyone comes up with.

This plugin does depend on nvim-orgmode but haven't really kept up with it's development lately

**Comment by akinsho** [comment]
This should be resolved now with the refactor, since the extmarks are now ephemeral and re-applied on every redraw the same way TS highlighting works (somewhat)

**Comment by jgollenz** [comment]
![org-bullets](https://user-images.githubusercontent.com/12050098/174137021-5b24de62-1f72-453e-8ae0-a81f71ad029e.gif)

Well, it looks like™ this is no longer happening, but I cannot confidently confirm it. The concealing seems to be broken for me, but I am experiencing similar behavior with link concealing in vanilla nvim-orgmode. If you have not experienced something similar with org-bullets, I'll look for a fix within nvim-orgmode first. 

But I'll trust your judgment on this particular issue, so feel free to close it. Not sure when I get time to thoroughly investigate the problems I encountered.

**Comment by akinsho** [comment]
@jgollenz that sounds promising, for my part I haven't noticed the issue anymore in any event the link concealing thing isn't really related to this problem as this only highlights headlines and checkboxes 🤷🏿
