### ISSUE TITLE
Checkmark only substitutes lower-case 'x'

### ISSUE THREAD

**Issue by jgollenz** [akinsho/org-bullets.nvim#12]
However, the default character that nvim-orgmode inserts with <C-space> seems to be upper-case 'X'. 

Fixed this in my fork: https://github.com/jgollenz/org-bullets.nvim/blob/fix/checkmark-ignore-case/lua/org-bullets.lua#L92
Shall I make a PR?

**Comment by jgollenz** [comment]
oh, and the Checkbox feature is not mentioned in the README. Only found it because I was poking around the PRs. Shall I include it?

**Comment by TravonteD** [comment]
Ah I see, it looks like we didn't run into this likely because `ignorecase` is a popular setting. Given the default is `false` for that option I think the PR should be made.
