### ISSUE TITLE
[Feature request] Conceal indented heading asterixes

### ISSUE THREAD

**Issue by ashincoder** [akinsho/org-bullets.nvim#2]
[![asciicast](https://asciinema.org/a/8jzM4YpLsPLbg49EsmQLQPaiX.svg)](https://asciinema.org/a/8jzM4YpLsPLbg49EsmQLQPaiX)

**Comment by ashincoder** [comment]
The following video showcases the problem. After one use of the bullet heading the others don't work

**Comment by akinsho** [comment]
@ashincoder this isn't a bug I believe because the way this plugin is written assumes that the correct todo headlines should not be indented. If you try your example again but without the indentation of the headline it should work. I *think* that in orgmode headlines aren't normally indented. If you find org mode docs saying they should/can be then please post them here and I'll update the plugin

**Comment by ashincoder** [comment]
It is indented in emacs orgmode

**Comment by ashincoder** [comment]
I will show it now in a video

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/127307840-b2eab3f5-66bf-4ba7-b7d9-1197df66c42e.mp4

**Comment by ashincoder** [comment]
I don't think it maybe be a bug. Just pointing it out. https://orgmode.org/manual/Org-Indent-Mode.html#Org-Indent-Mode. It can be set using org-indent-mode. In real org it can be set using `org-indent-mode`. I use doom-emacs. But I also tested it with vanilla emacs by using `emacs -q` and by enabling org-indent-mode the sub headlines are indented and thus the stars leaking are hided

**Comment by ashincoder** [comment]
I am currently in the process of learning lua. Otherwise I would really love to put a PR.

**Comment by akinsho** [comment]
@ashincoder it seems that this isn't default behaviour though and something you need to turn on a special setting for though right?

By default will org mode allow indenting of headlines? In either case not sure when I'll have time to look into this. It's primarily a matter of changing the vim regex this plugin uses to either allow optional whitespace or start at the beginning

https://github.com/akinsho/org-bullets.nvim/blob/6a9e15bc22dd8824b89ba053fc088c5644320bf2/lua/org-bullets.lua#L60

Maybe something like `^\s?` at the start like an optional lookbehind 🤷🏿‍♂️

**Comment by ashincoder** [comment]
Yeah we have to enable it in vanilla emacs. But in doom-emacs , the indent is by default

**Comment by ashincoder** [comment]
Should I keep this issue open ? Also no hurry. You can look into this whenever you think it is the right time. 
Maybe after I learn something I will try to make a PR. I am shitty amateur. :smile:

**Comment by akinsho** [comment]
@ashincoder feel free to leave it open, I'll to it at some point 👍🏿

**Comment by kristijanhusak** [comment]
@ashincoder exactly how you enable it in vanilla emacs? If there is an option for that in emacs, I should implement it in orgmode.nvim.

**Comment by ashincoder** [comment]
i think it is org-indent-mode

**Comment by ashincoder** [comment]
sorry for the late reply

**Comment by kristijanhusak** [comment]
Using `noindent` value in orgmode configuration should solve this specific issue for you, since there is no any indentation added. Problem is that it doesn't indent anything, so you will not have indentation where you expect it.

I'll make a PR here with the fix for this tomorrow.

**Comment by ashincoder** [comment]
> Using `noindent` value in orgmode configuration should solve this specific issue for you, since there is no any indentation added. Problem is that it doesn't indent anything, so you will not have indentation where you expect it.
> 
> I'll make a PR here with the fix for this tomorrow.

Nice :+1:

**Comment by kristijanhusak** [comment]
@ashincoder what is your `org-indent-mode` in emacs? I just tried installing org-bullets for emacs, and it still doesn't work like on the video, without any specific settings. This seems to be working like on video only when `org-indent-mode` is enabled. We cannot currently support that because there's no way to indent things only visually (at least not yet, hopefully in v0.6).

**Comment by ashincoder** [comment]
yeah it only works in `org-indent-mode`.

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/131348010-6872aebe-6a61-498f-884f-698d4fc2efcf.mp4

**Comment by ashincoder** [comment]
This is vanilla emacs.

**Comment by ashincoder** [comment]
The problem is that, after typing a main heading with a '*' then do a `return` then start writing another sub heading with '**' it will not accept it as a heading u have to move out of the indent to do another sub heading.

**Comment by kristijanhusak** [comment]
Enabled `org-indent-mode` creates a "virtual" indentation, which means that if you open up this org file from emacs in any other text editor, none of the text will be indented. Emacs has a way to create "virtual indents", but that's not yet possible in Neovim.

**Comment by ashincoder** [comment]
https://user-images.githubusercontent.com/83629316/131349539-6fa01856-a105-4454-a14e-881f346fd3e3.mp4

**Comment by ashincoder** [comment]
@kristijanhusak watch this u will understand more.

**Comment by kristijanhusak** [comment]
@ashincoder I understand what's the problem. I'm trying to explain why it works in emacs, and why we cannot solve it in Neovim at this moment.

**Comment by ashincoder** [comment]
Great atleast u understand what I am saying. :smile:

**Comment by kristijanhusak** [comment]
@ashincoder If you use this config for orgmode.nvim, it should properly work for this specific case in video:
```lua
require('orgmode').setup({
  org_indent_mode = 'noindent',
})
```

but none of the real content under a headline will be indented, because of the Neovim limitations.

**Comment by kristijanhusak** [comment]
@akinsho you can close this, since this is not an issue with your plugin.

@ashincoder If you wnat, I can give you small chunk of vimL code that will make this work for you every time you start the line with one or more `*`, even with enabled indents.

**Comment by ashincoder** [comment]
yeah I will close the issue and @kristijanhusak can give me the viml chunk :)

**Comment by nguyenhai97** [comment]
@kristijanhusak Can you share it with me as well?

**Comment by kristijanhusak** [comment]
@nguyenhai97 It is no longer needed. You can switch to nightly Neovim and use virtual indents https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#org_startup_indented
