### ISSUE TITLE
Is there a way to use this with norg-files?

### ISSUE THREAD

**Issue by azolus** [akinsho/org-bullets.nvim#26]
First of all: thank you for creating such a nice plugin. Little goodies like these really make day-to-day editing much more enjoyable!

I haven't been able to figure out how to enable the org-bullets for [norg-files](https://github.com/nvim-neorg/neorg). Using the default setup
```lua
use {'akinsho/org-bullets.nvim', config = function()
  require('org-bullets').setup()
end}
```
works fine if I manually `set ft=org`. This however is not a good solution, because I want the syntax support and the extra functionality that comes along with the `norg` filetype.

I am aware that through #25 it was possible to enable markdown support. It would be very helpful, if there were a guide on how to set this up with other filetypes (for me mainly `norg` and `markdown`), if possible. I'm sure other people would be very interested in how to set this up as well.

Otherwise, I think it would be great to have this feature, since `norg` files are very similar to traditional `org` files and readily supported by treesitter.

**Comment by akinsho** [comment]
Hi @azolus so I actually don't recommend using this plugin with `norg`. I actually use `neorg` from time to time, and that plugin has a good and complex system for concealing and replacing list icons/syntax. There's no way that this plugin could reliably work with it. I recommend instead looking into how that plugin's concealment works and configure it so it show the icons you want. I don't think an external plugin that ignores its own extension points is a good way to configure it.

**Comment by azolus** [comment]
Thanks for the reply. The built-in concealment works great, I was just assuming they used your plugin because it was mentioned a couple of times.
