### ISSUE TITLE
Adding orgmode-nvim topic

### ISSUE THREAD

**Issue by kristijanhusak** [akinsho/org-bullets.nvim#3]
Hi, could you add `orgmode-nvim` to your list of topics? That way plugin will be discoverable from here https://github.com/topics/orgmode-nvim. Thanks.

**Comment by akinsho** [comment]
Done 👍🏿 thanks for pointing it out 😄

**Comment by kristijanhusak** [comment]
Thanks. Just made the topic 10 min ago, so there wasn't anything to point out before :D
