### ISSUE TITLE
Re-editing an .org file invalidates ts-parser

### ISSUE THREAD

**Issue by tonico** [akinsho/org-bullets.nvim#30]
When I :edit an .org file for the first time then the org-bullets are applied. However, if I :edit the same file again then the org-bullets are not applied.

I guess the ts-parser is no longer valid when this happens. Adding the following code in `get_mark_positions()` fixes this for me:

```lua
  if not parser:is_valid() then
    parser:parse()
  end
```

**Comment by akinsho** [comment]
@tonico I haven't experienced this problem myself I think but please try https://github.com/akinsho/org-bullets.nvim/pull/31, it's a stab in the dark

**Comment by akinsho** [comment]
fixed by #31
