### ISSUE TITLE
Add support for list bullets and checkboxes

### ISSUE THREAD

**Issue by TravonteD** [akinsho/org-bullets.nvim#8]
I have a branch setup that supports using bullet characters for lists and checks for completed checkboxes. Before setting up a PR I wanted to get feedback on whether this should be included in this plugin or as apart of another.
![screenshot](https://user-images.githubusercontent.com/19380243/142745031-62a3f074-dbda-49d0-ae23-57aef674a757.png)

**Comment by akinsho** [comment]
Hi @TravonteD that seems cool, I definitely wouldn't mind a PR adding that 👍🏿

**Comment by akinsho** [comment]
fixed by #9
